language: python

cache:
    - ccache
    - pip

sudo: enabled

env:
    TOX_ENV=py34,py35,py36

install:
    - pip install -r requirements-development.txt

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y python-tox

script:
    - isort -c
    - flake8
    - tox -e $TOX_ENV

notifications:
      email:
          - travis@joaojunior.org
